# Configurações do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/menteleve_db
spring.datasource.username=postgres
spring.datasource.password=12345678

# Estratégia de atualização do banco (Cria as tabelas sozinho baseado no Java)
spring.jpa.hibernate.ddl-auto=update

# Mostrar no console as queries SQL que o Spring está fazendo (bom para aprender)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto do PostgreSQL para o Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect